### ISSUE TITLE
Basic example needs privilege escalation on linux

### ISSUE THREAD

**Issue by jimrthy** [SerenaFeng/tornado-swagger#2]
I forget where the cutoff lies (it may vary by distro), but linux restricts access to low-number ports (like 711). So you need sudo privileges to run basic.py.

**Comment by SerenaFeng** [comment]
Hi Jimrthy, thanks for pointing this out, basic.py is just an example to show how tornado-swagger works, the port number is changeable in the practical environment, for example, 8082 is leveraged in our official server.:)
